#
# Copyright (c) 2025 Karlsruhe Institute of Technology.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

spring.application.name=tora-game-management-service
spring.profiles.active=default

# Logging Configuration
logging.level.root=WARN
logging.level.org.springframework=WARN
logging.level.edu.kit.datamanager=DEBUG

# OpenAPI documentation
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.show-actuator=true

# Web Configuration
server.port=8080
spring.web.error.include-message=always
spring.main.allow-bean-definition-overriding=true

# Database Configuration
spring.datasource.driver-class-name=org.h2.Driver

# Next, please choose a location for the database file on your file system.
# WARNING: If no url is being defined, an in-memory database is being used,
#          loosing all data on restart.
# WARNING: Change the DB to be stored somewhere outside of /tmp!
spring.datasource.url=jdbc:h2:file:/tmp/database;MODE=LEGACY;NON_KEYWORDS=VALUE
spring.datasource.username=username
spring.datasource.password=secure_me
# Do not change ddl-auto if you do not know what you are doing:
# https://docs.spring.io/spring-boot/docs/1.1.0.M1/reference/html/howto-database-initialization.html
spring.jpa.hibernate.ddl-auto=update

